# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Science Sims @ CCNY
email: jhedberg@ccny.cuny.edu
description: > # this means to ignore newlines until "baseurl:"
  Science sims built for learners
baseurl: "/sims-site" # the subpath of your site, e.g. /blog
# url: "https://ccny-physics-sims.github.io/sims-site/" # the base hostname & protocol for your site
twitter_username:
github_username:  ccny-physics-sims

collections:
  sims:
    output: true
    permalink: sims/:title
    layout: sim
  tutorials:
    output: true
    permalink: tutorials/:title
    layout: sketch
  p5scripts:
    output: true
    permalink: p5scripts/:title
    layout: sketch


defaults:
  - scope:
      path: ""
      type: sims
    values:
      layout: sim
  - scope:
      path: ""
      type: tutorials
    values:
      layout: sketch
  - scope:
      path: ""
      type: p5scripts
    values:
      layout: sketch


# Build settings
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
