# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Science Sims @ CCNY
email: jhedberg@ccny.cuny.edu
description: > # this means to ignore newlines until "baseurl:"
  Science sims built for learners
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://ccny-physics-sims.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  ccny-physics-sims

collections:
  sims:
    output: true
    permalink: /sims/:title
    layout: sim

defaults:
  - scope:
      path: ""
      type: sims
    values:
      layout: sim

# Build settings
markdown: kramdown
